### ISSUE TITLE
Invalid receipts list results in unhandled TypeError exception

### ISSUE THREAD

**Issue by ldennison-bsd** [barrelstrength/craft-sprout-email#154]
If I attempt to save a basic notification (potentially any notification) with an invalid list format in the "To", the system gives me a TypeError exception. Specifically: 
```
Return value of barrelstrength\sproutbaseemail\controllers\NotificationsController::actionSaveNotificationEmail() must be an instance of yii\web\Response, null returned
in [...]/vendor/barrelstrength/sprout-base-email/src/controllers/NotificationsController.php at line 35
```

This happens at least when using the data ",whatever@example.com" (with the comma as the first character) in the "To" field. I'd guess that the comma-delimited list is being exploded but the resulting individual email elements are not being `trim()`'ed to eliminate empty strings. Regardless, I'd expect the system to tell me there's a formatting (or whatever) issue with the field instead of encountering an unhandled exception.

This was tested with devMode enabled. I do not know if it affects devMode disabled environments.

Relevant versions:
PHP: 7.4.5
Sprout Email: 4.2.0.1
Sprout Base: 5.1.3
Sprout Base Email: 1.2.8

**Comment by BenParizek** [comment]
@ldennison-bsd This is resolved in the latest release  v4.4.4.

The issue here is two-fold. The error show above is an issue with the methods type hint that we corrected a few releases ago. I believe that issue was blocking any error message from showing in this case. Once that's resolved, the errant comma does create an interesting scenario where the invalid email is an empty string "" so I've updated the error message to try to be a bit more clear in how it gets formatted for this case.
