### ISSUE TITLE
Cannot install plugin; league/csv and base-reports errors

### ISSUE THREAD

**Issue by mahajanl** [barrelstrength/craft-sprout-email#180]
### Description (screenshots, logs, ...)
Hi there, 

Running 3.5.19.1, trying to add plugin via composer require. The following errors appear, and even when requiring those additional pieces, I cannot get the plugin to show. I got close with hardcoding 4.1 into the composer.json, but then couldnt install the plugin. Advice and help would be amazing. 

Error received below:
`www-data@bdfd0a6e52f4:/var/www/src$ composer require barrelstrength/sprout-email
Using version ^4.4 for barrelstrength/sprout-email
./composer.json has been updated
Running composer update barrelstrength/sprout-email
Loading composer repositories with package information
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - barrelstrength/sprout-email[4.4.2, ..., v4.x-dev] require barrelstrength/sprout-base-reports ^1.5.2 -> satisfiable by barrelstrength/sprout-base-reports[1.5.2, ..., v1.x-dev].
    - barrelstrength/sprout-email[4.4.0, ..., 4.4.1] require barrelstrength/sprout-base-reports ^1.5.0 -> satisfiable by barrelstrength/sprout-base-reports[1.5.0, ..., v1.x-dev].
    - barrelstrength/sprout-base-reports[1.5.0, ..., 1.5.6] require league/csv ^8.2.0 -> found league/csv[8.2.0, 8.2.1, 8.2.2, 8.2.3] but the package is fixed to 9.5.0 (lock file version) by a partial update and that version does not match. Make sure you list it as an argument for the update command.
    - barrelstrength/sprout-base-reports[1.5.7, ..., v1.x-dev] require league/csv ^8.2.0|^9.6.1 -> found league/csv[dev-master, 8.2.0, 8.2.1, 8.2.2, 8.2.3, 9.6.1, ..., 9.x-dev (alias of dev-master)] but the package is fixed to 9.5.0 (lock file version) by a partial update and that version does not match. Make sure you list it as an argument for the update command.
    - Root composer.json requires barrelstrength/sprout-email ^4.4 -> satisfiable by barrelstrength/sprout-email[4.4.0, ..., v4.x-dev].

Use the option --with-all-dependencies (-W) to allow upgrades, downgrades and removals for packages currently locked to specific versions.

Installation failed, reverting ./composer.json and ./composer.lock to their original content.
www-data@bdfd0a6e52f4:/var/www/src$ 
`

### Steps to reproduce

1. in the terminal, type composer require barrelstrength/sprout-email
2. error appears. requiring the pieces it suggests leads to further errors. 

### Additional info

- Craft version: 3.5.19.1
- PHP version: 7.2
- Database driver & version:  
- Plugins & versions: 

Asset Rev | 6.0.2
-- | --
calendar 3.2.0
express forms 1.0.5
feedme 4.2.3
guest entries 2.3.0
redactor 2.8.4
SEO 3.6.5
template comment 1.1.2

_For some issues, we may request that you send the following items to Support <sprout@barrelstrengthdesign.com>. If you feel your issue may fall in that category, feel free to send things over after you post this issue and reference the issue in your email._

- `composer.json`
- `storage/logs/web.log` (or a zip of the whole log folder)
- An export of your database (or, if you can't share the whole db, the specific Sprout tables)

**Comment by BenParizek** [comment]
@mahajanl Do you need to upgrade to Craft 3.5 or can you update to the most recent version of Craft? If you can target the latest version of Craft and the latest version of the Sprout plugins this issue will likely go away.

If you need to update to Craft 3.5, we're going to need to hunt down the exact versions of all the Sprout Email dependencies at that release. Due to how Craft and Sprout updated composer requirements around that time, there is a scenario where if Sprout plugins can try to pull in dependencies for future versions of the software that aren't compatible with other packages required with the Sprout versions that work with Craft 3.5.

Let me know if we need to hunt down those other version numbers or if you can get around this by updating to the latest.

**Comment by mahajanl** [comment]
Hi there,

Thanks for the speedy reply! Very appreciated. for a bunch of reasons, we
need to stay for now on 3.5.19.1 because the clients server is still on php
7.2 and there's a whole lot of other things going on there I won't bore you
with.

I think this means we need to go hunting. If this is something I can do on
my own and you could give direction with, that would be awesome. Also
please let me know if i've misunderstood something from what you said.

Thanks again!

Lakshami Mahajan
Developer
for The Refinery <http://the-refinery.io>
Freelance Developer

**Comment by BenParizek** [comment]
No problem, it's just a bit more tedious to explain and sometimes requires a bit of troubleshooting along the way. If the below doesn't make sense, or if you get tripped up along the way, feel free to drop me a note (sprout@barrelstrengthdesign.com) and we can work through it on a screen share. This issue is really just about troubleshooting composer error messages.

In looking closer at the error, I'm not positive this is a sprout package issue or if it's just a conflict between sprout-base-reports and feed me requiring different versions of league CSV and your lock file. I see you say that the flag you used ignores locked versions but one of the errors is:

> _barrelstrength/sprout-base-reports[1.5.7, ..., v1.x-dev] require league/csv ^8.2.0|^9.6.1 -> found league/csv[dev-master, 8.2.0, 8.2.1, 8.2.2, 8.2.3, 9.6.1, ..., 9.x-dev (alias of dev-master)] **but the package is fixed to 9.5.0 (lock file version)** by a partial update and that version does not match. Make sure you list it as an argument for the update command._

Have you tried deleted the `vendor/` folder and `composer.lock` file and re-running the `composer update` from scratch?

It looks like Feed Me requires `"league/csv": "^8.2 || ^9.0"` where Sprout Base Reports requires `"league/csv": "^8.2.0|^9.6.1"` so reports will throw an error like above if you have a composer.lock indicated the version is locked at 9.5.

**Comment by mahajanl** [comment]
Thank you so much. We no longer need FeedMe on here, and uninstalling it
did the trick.

Appreciated!!

Lakshami Mahajan
Developer
for The Refinery <http://the-refinery.io>
Freelance Developer
