### ISSUE TITLE
User not permitted to perform this action 

### ISSUE THREAD

**Issue by DrewBold** [barrelstrength/craft-sprout-email#184]
### Description (screenshots, logs, ...)

Craft user Permissions: 
Super User (All craft permissions except Administer users) 

![image](https://user-images.githubusercontent.com/66840687/138750371-b112efeb-67f2-43bc-8073-3bfe92d025ad.png)

### Steps to reproduce

1. Attempt to save new or edit existing sprout email notification
2. Error is thrown 

### Additional info

- Craft version: 3.5.17.1
- PHP version: 7.3.16
- Database driver & version:  MySQL 5.6.22
- Plugins & versions: Sprout Email Pro 4.4.9

**Comment by BenParizek** [comment]
@DrewBold Unfortunately the issue here is deeper than a quick fix and relates to a bad architectural decision I made in our base modules. I'm working on a fix to address this and the underlying issues in our next major release but can't promise a timeline on that yet. 

For now, it will be necessary to be an admin to edit those entries, or, I can't officially recommend this as a solution as I haven't fully tested it, but you can potentially work around the issue by manually adding a permission in the database:

In the `craft_userpermissions` table you can add a new row and a permission called `global-editnotifications` in the `craft_userpermissions.name` column.

And then, in the `craft_userpermissions_users` table, you will need to make sure the user who you want to have that permission is matched to the permission ID of the row you just created above:

`craft_userpermissions_users.permissionId` = The ID created in the row above
`craft_userpermissions_users.userId` = The user ID of who you want to be able to edit that page

I won't be able to clean those settings up for you in a future migration so you'll have to do that manually if you go this route, or they may just become orphaned. 

I'm going to merge this with another ticket on the same topic:
https://github.com/barrelstrength/craft-sprout-email/issues/178
