### ISSUE TITLE
Sent Emails Limit - doesn't remove rows from db

### ISSUE THREAD

**Issue by darylknight** [barrelstrength/craft-sprout-email#99]
### Description

Changing the Sent Emails Limit in the control panel removes the entries from the control panel, but doesn't remove the rows in the database. For example, changing the limit to 100 still has 6700 rows in the `sproutemail_sentemail` table (even after the task to clear up the table has finished running).

- Craft version: 3.1.8
- PHP version: 7.3
- Database driver & version: MySQL
- Plugins & versions: 4.0.0-beta.9

**Comment by pdaleramirez** [comment]
@darylknight I submitted an issue about this bug on Craft cms core here https://github.com/craftcms/cms/issues/3833 
This happens on other Element as well. I review this again once i get feedback to my submitted issue, If you really want to remove those you can manually remove those records in the database.

**Comment by BenParizek** [comment]
@darylknight P&T responded in that other thread and say this is because of the new Soft Delete behavior in Craft 3.1. It looks like there is a `softDeleteDuration` [config setting](https://docs.craftcms.com/v3/config/config-settings.html#softdeleteduration) if you want to adjust that. I'll consider this resolved but if the quantity causes any issues, feel free to reopen and we can consider updating the behavior here.
